[workspace]
authors = ["Ivan Domrachev <i_domrachev@kaist.ac.kr>"]
channels = ["robostack-humble", "conda-forge"]
name = "phantom_sim"
platforms = ["osx-arm64"]
version = "0.1.0"

[activation]
scripts = ["scripts/activate.sh", "install/setup.sh"]

[tasks]
build = { cmd = "colcon build --symlink-install --cmake-args -G Ninja -DCMAKE_EXPORT_COMPILE_COMMANDS=ON && python scripts/merge_compile_commands.py", inputs = ["src"], outputs = ["build", "install", "compile_commands.json"] }
sim = {cmd = "pixi run ros2 run phantom_sim simulator_node", depends-on = ["build"] }
controller = {cmd = "ros2 run phantom_controllers base_controller_node", depends-on = ["build"]}
gravity_comp = {cmd = "ros2 run phantom_controllers base_controller_node --ros-args -p gravity_compensation:=true", depends-on = ["build"]}
rviz = { cmd = "ros2 run rviz2 rviz2 -d install/phantom_sim/share/phantom_sim/rviz/phantom.rviz", depends-on = ["build"]}
plot = { cmd = "ros2 run plotjuggler plotjuggler --layout install/phantom_sim/share/phantom_sim/plotjuggler/joint_states.xml", depends-on = ["build"]}
all = { cmd = "ros2 launch phantom_sim sim.launch.py", depends-on = ["build"] }

[dependencies]
# ROS2
ros-humble-rclcpp = "*"
ros-humble-std-msgs = "*"
ros-humble-sensor-msgs = "*"
ros-humble-geometry-msgs = "*"
ros-humble-tf2-ros = "*"
ros-humble-rviz2 = "*"
ros-humble-ament-cmake = "*"
ros-humble-ament-index-cpp = "*"
ros-humble-launch-ros = "*"

# Build tools
colcon-common-extensions = "*"
compilers = "*"
cmake = "<4"
ninja = "*"
pkg-config = "*"

# Libraries
casadi = "*"
yaml-cpp = "*"
ros-humble-ros2cli = ">=0.18.17,<0.19"
ros-humble-ros2run = ">=0.18.17,<0.19"
ros-humble-ros2topic = ">=0.18.17,<0.19"
ros-humble-ros2launch = ">=0.19.13,<0.20"
ros-humble-plotjuggler-ros = "*"
